### ISSUE TITLE
Initial update() fails with sqlite3.OperationalError: no such table: status

### ISSUE THREAD

**Issue by redpoint13** [HansjoergW/sec-fincancial-statement-data-set#2]
In attempting to do first runs of secfsdstools, it yields the error:

sqlite3.OperationalError: no such table: status

The error points to an issue where a sqlite3 table does not exist.  A search of the code did not reveal any sqlite setup instructions.

Is there a script you could share to perform the initial sqlite database setup?

Here are the steps to reproduce the error. Using a fresh install with no database setup
>>> from secfsdstools.update import update
>>> update()
and the error:
2023-08-29 22:39:08,469 [INFO] configmgt  reading configuration from /root/.secfsdstools.cfg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/secanalyzing/lib/python3.10/site-packages/secfsdstools/update.py", line 27, in update
    config = ConfigurationManager.read_config_file()
  File "/opt/conda/envs/secanalyzing/lib/python3.10/site-packages/secfsdstools/a_config/configmgt.py", line 94, in read_config_file
    return ConfigurationManager._read_configuration_and_check_for_udpates(home_cfg_file_path)
  File "/opt/conda/envs/secanalyzing/lib/python3.10/site-packages/secfsdstools/a_config/configmgt.py", line 144, in _read_configuration_and_check_for_udpates
    ConfigurationManager._check_for_update(config)
  File "/opt/conda/envs/secanalyzing/lib/python3.10/site-packages/secfsdstools/a_config/configmgt.py", line 152, in _check_for_update
    updater.update()
  File "/opt/conda/envs/secanalyzing/lib/python3.10/site-packages/secfsdstools/c_update/updateprocess.py", line 146, in update
    if not self._check_for_update():
  File "/opt/conda/envs/secanalyzing/lib/python3.10/site-packages/secfsdstools/c_update/updateprocess.py", line 70, in _check_for_update
    last_check = self.db_state_accesor.get_key(Updater.LAST_UPDATE_CHECK_KEY)
  File "/opt/conda/envs/secanalyzing/lib/python3.10/site-packages/secfsdstools/a_utils/dbutils.py", line 225, in get_key
    result = self.execute_fetchall(sql)
  File "/opt/conda/envs/secanalyzing/lib/python3.10/site-packages/secfsdstools/a_utils/dbutils.py", line 87, in execute_fetchall
    return conn.execute(sql).fetchall()
sqlite3.OperationalError: no such table: status

**Comment by HansjoergW** [comment]
Hi Tony

Sorry for that, that should happen automatically. I assume you are on
version 0.5.1?

There is a class DbCreator() (
https://github.com/HansjoergW/sec-fincancial-statement-data-set/blob/v0.5.1/secfsdstools/b_setup/setupdb.py)
which takes care of that.

----
from secfsdstools.b_setup.setupdb import DbCreator
DbCreator(db_dir="<path>").create_db()
---

<path> is the path that is configured inside the config file under
"dbdirectory".

Please let me know if this solves he problem.

Cheers
Hansjörg


Am Mi., 30. Aug. 2023 um 01:21 Uhr schrieb Tony Shouse <
***@***.***>:

**Comment by redpoint13** [comment]
Thank you. Update() is now running for the initial setup.
